# Site settings
title: AthenaK Summer School
email: david.radice@psu.edu
url: https://dradice.github.io/athenak-summer-school/
description: "AthenaK summer school is a 2-weeks summer school on computational astrophysics with the AthenaK code."
keywords: "AthenaK, MHD, astrophysics, numerical relativity, Penn State University"
skills: "Get started with AthenaK, learn how to use the code, and apply it to astrophysical problems."
meta_author: Radice David

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Application form using formspree.io
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c5aa0
  primary-rgb: "44,90,160"
  secondary: 1a252f
  secondary-dark: 0f1419

# Footer settings
footer:
  copyright: David Radice
  location: Penn State University

# Postal address (add as many lines as necessary)
address:
  - line: 251 Pollock Road
  - line: University Park, PA 16802

# Credits content
credits: 'David Radice'

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  instructors:
    output: false

#for instructors
defaults:
  - scope:
      path: ""
      type: "instructors"
    values:
      layout: "default"
